### PR TITLE
Support ipv6 addresses in logs

### PR DESCRIPTION
**Pull request by Sophist-UK**
This fix simplifies the ipv4 regex and adds support for recognising ipv6
addresses in log files for %a and %A.

Note: In the interests of simplicity we assume that ipv6 addresses in
log files will be valid, and the ipv6 regex does will recognise all
valid ipv6 addresses but will also pass some invalid ipv6 addresses i.e.
1:1:1:1:1:1:1::1:1:1:1:1:1:1 will pass.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Any news on this PR? My ISP supports ipv6 connections to my web site, so this plugin needs to handle IPv6 addresses in the server logs.

**Comment by Sophist-UK** [comment]
Neither merged nor commented on.

Any news?

**Comment by kassner** [comment]
Hi @Sophist-UK 

Sorry for the long delay. I was hoping to add some tests to IPv6 addresses, but it seems very difficult to find a good regex that does not fail in some edge cases.

If you (or anyone reading here) is interested in contributing with IPv6 tests, [there is a good list](https://github.com/gws/ipv6-address-test/blob/21d088ebd0edbb2a8fc07c424304cb6629813f1d/Tests/Ipv6TestCase.php) of valid and invalid IPv6 addresses to take a look on.

Thanks!

**Comment by Sophist-UK** [comment]
The regex used was the result of reasonably extensive internet research.

However, for the purposes of log parsing, it is probably not essential for the regex to identify edge cases.

**Comment by Sophist-UK** [comment]
P.S. Apologies - but I realise that I have not added any automated tests.

**Pull request merged**
