### PR TITLE
Support PHP 8.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This PR tests the codebase on PHP 8.0. In order to to do this, I had to refactor the static analysis stuff to only be installed on, and run on PHP 7.4 on Actions.

---

Note that Your GitHub Actions settings in the repo are preventing all the jobs from showing up in this PR. After this is merged, all the jobs will show up again. You can see the build status on my fork for this PR: https://github.com/GrahamCampbell/log-parser/actions/runs/351095169, https://github.com/GrahamCampbell/log-parser/actions/runs/351095168.

### CODE REVIEW

**Comment by kassner** [comment]
Hi @GrahamCampbell, thanks for your PR!

It will take me a while to understand the trade-offs with `bamarni/composer-bin-plugin`, so I'll likely split this PR to better address each change.

Also, I _depend a lot_ on Dependabot (lol) at work, I'm not sure I want to disable it in this repository without testing how things work out first.

Thanks again for your PR, let me see what I can do.

**Comment by GrahamCampbell** [comment]
Dependabot only makes sense for apps (in most cases). It is usual to not commit a lock file for libraries.

The bin-plugin refactor was not just a refactor. It was genuinely needed in order to run the tests on PHP 8.0, since some of the static analysis tools don't support PHP 8.

**Comment by kassner** [comment]
Yeah I am aware of that. Tried to test with PHP 8 yesterday and PHP-CS-Fixer isn't ready for it yet.

**Comment by GrahamCampbell** [comment]
NB Dependabot has no use here, since you have no depencenies, and no lock file.

**Comment by GrahamCampbell** [comment]
Friendly ping. :)

**Comment by kassner** [comment]
This PR doesn't seem to fix a problem I have. If I happen to stumble upon this problem in the future, it will be considered.

**Pull request closed without merging**
